# Generated by Django 5.0.7 on 2024-07-24 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_image_url_alter_post_date_alter_post_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image_url',
        ),
        migrations.AddField(
            model_name='post',
            name='banner',
            field=models.ImageField(blank=True, default='static/ac.jpg', max_length=200, upload_to=''),
        ),
    ]
